/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3dModels/ground.glb --transform --types --output src/app/components/3d/ground.tsx 
Files: 3dModels/ground.glb [29.84KB] > D:\Dev\Astrologics\src\app\components\3d\ground-transformed.glb [11.5KB] (61%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Ground(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ground-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} scale={1.583} />
    </group>
  )
}

useGLTF.preload('/ground-transformed.glb')
