/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3dModels/lantern.glb --transform --types --output src/app/components/3d/models/Lantern.tsx 
Files: 3dModels/lantern.glb [8.22MB] > D:\Dev\Astrologics\src\app\components\3d\models\lantern-transformed.glb [900.96KB] (89%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
  }
  materials: {
    lantern_chandelier_01: THREE.MeshStandardMaterial
    lantern_chandelier_01_glass: THREE.MeshPhysicalMaterial
    lantern_chandelier_01_lamp: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Lantern(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/lantern-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.686}>
        <mesh geometry={nodes.Plane001.geometry} material={materials.lantern_chandelier_01} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.lantern_chandelier_01_glass} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials.lantern_chandelier_01_lamp} />
      </group>
    </group>
  )
}

useGLTF.preload('/lantern-transformed.glb')
