/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3dModels/office.glb --transform --types --output src/app/components/3d/office.tsx 
Files: 3dModels/office.glb [237.52KB] > D:\Dev\Astrologics\src\app\components\3d\office-transformed.glb [85.48KB] (64%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['static-floor']: THREE.Mesh
    navMesh: THREE.Mesh
  }
  materials: {
    gridbox: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Office(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/office-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['static-floor'].geometry} material={materials.gridbox} />
      <mesh geometry={nodes.navMesh.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/office-transformed.glb')
