/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useMemo, useRef } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useCurrentSheet } from '@theatre/r3f'
import { types } from '@theatre/core'
import { GLTF, SkeletonUtils } from 'three-stdlib'

// ActionName and GLTFResult types remain the same as your source file...

const MINION_THEATRE_PROPS = {
  // Transform Props (Standard)
  transform: types.compound({
    position: types.compound({
      x: types.number(0, { nudgeMultiplier: 0.1 }),
      y: types.number(0, { nudgeMultiplier: 0.1 }),
      z: types.number(0, { nudgeMultiplier: 0.1 }),
    }),
    rotation: types.compound({
      x: types.number(0, { nudgeMultiplier: 0.01 }),
      y: types.number(0, { nudgeMultiplier: 0.01 }),
      z: types.number(0, { nudgeMultiplier: 0.01 }),
    }),
    scale: types.number(1, { range: [0, 5], nudgeMultiplier: 0.1 }),
  }),
  
  // Animation Blending (Core)
  animations: types.compound({
    Walking_A: types.number(0, { range: [0, 1] }),
    Idle: types.number(0, { range: [0, 1] }),
    Spellcasting: types.number(0, { range: [0, 1] }),
    Spawn_Ground: types.number(0, { range: [0, 1] }),
    Death_A: types.number(0, { range: [0, 1] }),
  }),

  // Advanced Visuals (Profit-Focused)
  visuals: types.compound({
    globalTimeScale: types.number(1, { range: [0, 2] }),
    opacity: types.number(1, { range: [0, 1] }),
    glowIntensity: types.number(1, { range: [0, 10] }), // Control the 'Glow' material
    visible: types.boolean(true),
  }),
}

export function SkeletonMinion(props: React.ComponentPropsWithoutRef<'group'>) {
  const group = useRef<THREE.Group>(null!)
  const sheet = useCurrentSheet()
  
  const { scene, animations } = useGLTF('/Skeleton_Minion-transformed.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions, mixer } = useAnimations(animations, group)

  const theatreObj = useMemo(() => {
    return sheet?.object('minion_master_controls', MINION_THEATRE_PROPS)
  }, [sheet])

  useFrame(() => {
    if (!theatreObj || !actions) return

    const { transform, animations: animValues, visuals } = theatreObj.value

    // 1. APPLY TRANSFORMS
    group.current.position.set(transform.position.x, transform.position.y, transform.position.z)
    group.current.rotation.set(transform.rotation.x, transform.rotation.y, transform.rotation.z)
    group.current.scale.setScalar(transform.scale)

    // 2. APPLY ANIMATIONS
    Object.keys(animValues).forEach((key) => {
      const action = actions[key as ActionName]
      if (action) {
        action.play().paused = false
        action.setEffectiveWeight(animValues[key])
      }
    })

    // 3. APPLY ADVANCED VISUALS
    mixer.timeScale = visuals.globalTimeScale
    group.current.visible = visuals.visible
    
    // Update Material Opacity (requires transparent: true)
    materials.skeleton.transparent = true
    materials.skeleton.opacity = visuals.opacity
    
    // Update Glow Intensity (if using Emissive materials)
    materials.Glow.emissiveIntensity = visuals.glowIntensity
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rig">
          <primitive object={nodes.root} />
        </group>
        <skinnedMesh name="Skeleton_Minion_ArmLeft" geometry={nodes.Skeleton_Minion_ArmLeft.geometry} material={materials.skeleton} skeleton={nodes.Skeleton_Minion_ArmLeft.skeleton} castShadow />
        <skinnedMesh name="Skeleton_Minion_ArmRight" geometry={nodes.Skeleton_Minion_ArmRight.geometry} material={materials.skeleton} skeleton={nodes.Skeleton_Minion_ArmRight.skeleton} castShadow />
        <skinnedMesh name="Skeleton_Minion_Body" geometry={nodes.Skeleton_Minion_Body.geometry} material={materials.skeleton} skeleton={nodes.Skeleton_Minion_Body.skeleton} castShadow />
        <skinnedMesh name="Skeleton_Minion_Cloak" geometry={nodes.Skeleton_Minion_Cloak.geometry} material={materials.skeleton} skeleton={nodes.Skeleton_Minion_Cloak.skeleton} castShadow />
        <skinnedMesh name="Skeleton_Minion_Eyes" geometry={nodes.Skeleton_Minion_Eyes.geometry} material={materials.Glow} skeleton={nodes.Skeleton_Minion_Eyes.skeleton} />
        <skinnedMesh name="Skeleton_Minion_Head" geometry={nodes.Skeleton_Minion_Head.geometry} material={materials.skeleton} skeleton={nodes.Skeleton_Minion_Head.skeleton} castShadow />
        <skinnedMesh name="Skeleton_Minion_Jaw" geometry={nodes.Skeleton_Minion_Jaw.geometry} material={materials.skeleton} skeleton={nodes.Skeleton_Minion_Jaw.skeleton} castShadow />
        <skinnedMesh name="Skeleton_Minion_LegLeft" geometry={nodes.Skeleton_Minion_LegLeft.geometry} material={materials.skeleton} skeleton={nodes.Skeleton_Minion_LegLeft.skeleton} castShadow />
        <skinnedMesh name="Skeleton_Minion_LegRight" geometry={nodes.Skeleton_Minion_LegRight.geometry} material={materials.skeleton} skeleton={nodes.Skeleton_Minion_LegRight.skeleton} castShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/Skeleton_Minion-transformed.glb')