
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  mobile: 'mobile',
  email: 'email',
  passwordHash: 'passwordHash',
  avatar: 'avatar',
  isActive: 'isActive',
  isDeleted: 'isDeleted',
  emailVerified: 'emailVerified',
  mobileVerified: 'mobileVerified',
  lastLoginAt: 'lastLoginAt',
  totalGenerations: 'totalGenerations',
  totalStorageUsed: 'totalStorageUsed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NativityChartScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  description: 'description',
  birthDateTime: 'birthDateTime',
  birthTimestamp: 'birthTimestamp',
  timeResolution: 'timeResolution',
  coordinateSystem: 'coordinateSystem',
  latitude: 'latitude',
  longitude: 'longitude',
  timezone: 'timezone',
  locationName: 'locationName',
  isPublic: 'isPublic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EphemerisSnapshotScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  absoluteTimeIndex: 'absoluteTimeIndex',
  phase: 'phase',
  createdAt: 'createdAt'
};

exports.Prisma.PlanetDataScalarFieldEnum = {
  id: 'id',
  ephemerisSnapshotId: 'ephemerisSnapshotId',
  planet: 'planet',
  longitude: 'longitude',
  latitude: 'latitude',
  speed: 'speed',
  acceleration: 'acceleration',
  direction: 'direction',
  stationaryEnterTime: 'stationaryEnterTime',
  stationaryExitTime: 'stationaryExitTime',
  houseCusp: 'houseCusp',
  houseDegree: 'houseDegree',
  houseSign: 'houseSign',
  relativeAngularIndex: 'relativeAngularIndex',
  createdAt: 'createdAt'
};

exports.Prisma.GeometryIndexScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  clusterHash: 'clusterHash',
  createdAt: 'createdAt'
};

exports.Prisma.AngularDistanceScalarFieldEnum = {
  id: 'id',
  geometryIndexId: 'geometryIndexId',
  planet1: 'planet1',
  planet2: 'planet2',
  distance: 'distance',
  minDistance: 'minDistance',
  maxDistance: 'maxDistance',
  speedWeighting: 'speedWeighting',
  createdAt: 'createdAt'
};

exports.Prisma.NativityAspectScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  geometryIndexId: 'geometryIndexId',
  planet1: 'planet1',
  planet2: 'planet2',
  aspectType: 'aspectType',
  orbDistance: 'orbDistance',
  isApplying: 'isApplying',
  exactnessScore: 'exactnessScore',
  exactDateTime: 'exactDateTime',
  buildUpStart: 'buildUpStart',
  decayEnd: 'decayEnd',
  orbStrength: 'orbStrength',
  speedWeighting: 'speedWeighting',
  planet1ProfileId: 'planet1ProfileId',
  planet2ProfileId: 'planet2ProfileId',
  createdAt: 'createdAt'
};

exports.Prisma.PlanetaryProfileScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  planet: 'planet',
  primaryDomain: 'primaryDomain',
  secondaryDomain: 'secondaryDomain',
  dignity: 'dignity',
  strength: 'strength',
  speed: 'speed',
  visibility: 'visibility',
  expressionBandwidth: 'expressionBandwidth',
  saturationLevel: 'saturationLevel',
  distortionFactor: 'distortionFactor',
  housePosition: 'housePosition',
  signPosition: 'signPosition',
  createdAt: 'createdAt'
};

exports.Prisma.StateVectorScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  timestamp: 'timestamp',
  timestampMicro: 'timestampMicro',
  planetaryStates: 'planetaryStates',
  aspectStates: 'aspectStates',
  outcomes: 'outcomes',
  decisions: 'decisions',
  narratives: 'narratives',
  eventLayer: 'eventLayer',
  patternLayer: 'patternLayer',
  archetypeLayer: 'archetypeLayer',
  confidenceLevel: 'confidenceLevel',
  entropyScore: 'entropyScore',
  createdAt: 'createdAt'
};

exports.Prisma.PurposeStateScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  timestamp: 'timestamp',
  timestampMicro: 'timestampMicro',
  planetaryStates: 'planetaryStates',
  aspectStates: 'aspectStates',
  outcomes: 'outcomes',
  decisions: 'decisions',
  narratives: 'narratives',
  intentSignals: 'intentSignals',
  priorityWeights: 'priorityWeights',
  constraintFlags: 'constraintFlags',
  purposeVector: 'purposeVector',
  vectorVersion: 'vectorVersion',
  computedAt: 'computedAt',
  confidenceLevel: 'confidenceLevel',
  entropyScore: 'entropyScore',
  createdAt: 'createdAt'
};

exports.Prisma.SimilarityRecordScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  similarTo: 'similarTo',
  similarityScore: 'similarityScore',
  speedWeighting: 'speedWeighting',
  phaseWeighting: 'phaseWeighting',
  orbWeighting: 'orbWeighting',
  queryType: 'queryType',
  createdAt: 'createdAt'
};

exports.Prisma.CurrentStoryScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  transitDate: 'transitDate',
  userLatitude: 'userLatitude',
  userLongitude: 'userLongitude',
  userTimeZone: 'userTimeZone',
  storyState: 'storyState',
  mainNarrative: 'mainNarrative',
  overallIntensity: 'overallIntensity',
  themes: 'themes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.PlanetarySceneScalarFieldEnum = {
  id: 'id',
  currentStoryId: 'currentStoryId',
  planet: 'planet',
  sign: 'sign',
  house: 'house',
  natalLongitude: 'natalLongitude',
  currentLongitude: 'currentLongitude',
  movementDegrees: 'movementDegrees',
  intensity: 'intensity',
  dominantPressure: 'dominantPressure',
  behavioralPattern: 'behavioralPattern',
  externalConflict: 'externalConflict',
  relationshipEffect: 'relationshipEffect',
  pressureDirection: 'pressureDirection',
  collapseRisk: 'collapseRisk',
  momentumDirection: 'momentumDirection',
  storyFunction: 'storyFunction',
  activeAspects: 'activeAspects',
  sceneAttributes: 'sceneAttributes',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};
exports.TimeResolution = exports.$Enums.TimeResolution = {
  MINUTE: 'MINUTE',
  SECOND: 'SECOND',
  EVENT_BASED: 'EVENT_BASED'
};

exports.CoordinateSystem = exports.$Enums.CoordinateSystem = {
  SIDEREAL: 'SIDEREAL',
  TROPICAL: 'TROPICAL'
};

exports.PlanetDirection = exports.$Enums.PlanetDirection = {
  DIRECT: 'DIRECT',
  RETROGRADE: 'RETROGRADE',
  STATIONARY: 'STATIONARY'
};

exports.Prisma.ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  NativityChart: 'NativityChart',
  EphemerisSnapshot: 'EphemerisSnapshot',
  PlanetData: 'PlanetData',
  GeometryIndex: 'GeometryIndex',
  AngularDistance: 'AngularDistance',
  NativityAspect: 'NativityAspect',
  PlanetaryProfile: 'PlanetaryProfile',
  StateVector: 'StateVector',
  PurposeState: 'PurposeState',
  SimilarityRecord: 'SimilarityRecord',
  CurrentStory: 'CurrentStory',
  PlanetaryScene: 'PlanetaryScene'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
