
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  mobile: 'mobile',
  email: 'email',
  passwordHash: 'passwordHash',
  avatar: 'avatar',
  isActive: 'isActive',
  isDeleted: 'isDeleted',
  emailVerified: 'emailVerified',
  mobileVerified: 'mobileVerified',
  lastLoginAt: 'lastLoginAt',
  totalGenerations: 'totalGenerations',
  totalStorageUsed: 'totalStorageUsed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AIGenerationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  utilityType: 'utilityType',
  mode: 'mode',
  status: 'status',
  errorMessage: 'errorMessage',
  sourceImageId: 'sourceImageId',
  resultImageId: 'resultImageId',
  referenceImageId: 'referenceImageId',
  presetId: 'presetId',
  presetLabel: 'presetLabel',
  customPrompt: 'customPrompt',
  roomType: 'roomType',
  goal: 'goal',
  gender: 'gender',
  category: 'category',
  model: 'model',
  promptUsed: 'promptUsed',
  apiResponse: 'apiResponse',
  processingTime: 'processingTime',
  creditsConsumed: 'creditsConsumed',
  estimatedCost: 'estimatedCost',
  rating: 'rating',
  comment: 'comment',
  isPublic: 'isPublic',
  shareId: 'shareId',
  tags: 'tags',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completedAt: 'completedAt'
};

exports.Prisma.UploadedFileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fileName: 'fileName',
  fileSize: 'fileSize',
  mimeType: 'mimeType',
  fileType: 'fileType',
  status: 'status',
  storagePath: 'storagePath',
  storageUrl: 'storageUrl',
  gcsBucket: 'gcsBucket',
  width: 'width',
  height: 'height',
  format: 'format',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  uploadedAt: 'uploadedAt'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  planType: 'planType',
  pricingPlanId: 'pricingPlanId',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  autoRenew: 'autoRenew',
  maxGenerationsPerMonth: 'maxGenerationsPerMonth',
  maxGenerationsPerDay: 'maxGenerationsPerDay',
  maxStorageMB: 'maxStorageMB',
  maxHairstyleGenerations: 'maxHairstyleGenerations',
  maxMakeupGenerations: 'maxMakeupGenerations',
  maxHomeDecoGenerations: 'maxHomeDecoGenerations',
  maxLinkedInGenerations: 'maxLinkedInGenerations',
  maxBirthChartGenerations: 'maxBirthChartGenerations',
  maxAstrologyReadings: 'maxAstrologyReadings',
  maxTransitCharts: 'maxTransitCharts',
  maxCompatibilityCharts: 'maxCompatibilityCharts',
  features: 'features',
  price: 'price',
  currency: 'currency',
  paymentMethod: 'paymentMethod',
  paymentId: 'paymentId',
  lastPaymentAt: 'lastPaymentAt',
  billingCycle: 'billingCycle',
  nextBillingDate: 'nextBillingDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UsageLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  subscriptionId: 'subscriptionId',
  generationId: 'generationId',
  utilityType: 'utilityType',
  action: 'action',
  creditsConsumed: 'creditsConsumed',
  cost: 'cost',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.UserPreferencesScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  defaultHairstyleMode: 'defaultHairstyleMode',
  defaultMakeupMode: 'defaultMakeupMode',
  defaultHomeDecoMode: 'defaultHomeDecoMode',
  defaultLinkedInMode: 'defaultLinkedInMode',
  defaultReadingTypes: 'defaultReadingTypes',
  birthTimeFormat: 'birthTimeFormat',
  zodiacSystem: 'zodiacSystem',
  houseSystem: 'houseSystem',
  preferredAspects: 'preferredAspects',
  showMinorAspects: 'showMinorAspects',
  notifyOnSignificantTransits: 'notifyOnSignificantTransits',
  favoriteHairstylePresets: 'favoriteHairstylePresets',
  favoriteMakeupPresets: 'favoriteMakeupPresets',
  favoriteHomeDecoPresets: 'favoriteHomeDecoPresets',
  favoriteLinkedInPresets: 'favoriteLinkedInPresets',
  theme: 'theme',
  language: 'language',
  showTutorials: 'showTutorials',
  autoSaveHistory: 'autoSaveHistory',
  emailNotifications: 'emailNotifications',
  pushNotifications: 'pushNotifications',
  notifyOnCompletion: 'notifyOnCompletion',
  defaultSharePublic: 'defaultSharePublic',
  preferredImageQuality: 'preferredImageQuality',
  autoDeleteOldFiles: 'autoDeleteOldFiles',
  fileRetentionDays: 'fileRetentionDays',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BirthChartScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  chartType: 'chartType',
  chartName: 'chartName',
  birthDate: 'birthDate',
  birthTime: 'birthTime',
  birthTimezone: 'birthTimezone',
  birthLocation: 'birthLocation',
  latitude: 'latitude',
  longitude: 'longitude',
  altitude: 'altitude',
  sunSign: 'sunSign',
  moonSign: 'moonSign',
  risingSign: 'risingSign',
  moonPhase: 'moonPhase',
  lunarDay: 'lunarDay',
  isCalculated: 'isCalculated',
  calculationError: 'calculationError',
  notes: 'notes',
  isPublic: 'isPublic',
  shareId: 'shareId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  calculatedAt: 'calculatedAt'
};

exports.Prisma.PlanetPositionScalarFieldEnum = {
  id: 'id',
  birthChartId: 'birthChartId',
  planet: 'planet',
  zodiacSign: 'zodiacSign',
  degree: 'degree',
  minutes: 'minutes',
  seconds: 'seconds',
  house: 'house',
  houseDegree: 'houseDegree',
  speed: 'speed',
  isRetrograde: 'isRetrograde',
  element: 'element',
  quality: 'quality',
  isDomicile: 'isDomicile',
  isExaltation: 'isExaltation',
  isDetriment: 'isDetriment',
  isFall: 'isFall',
  dignityScore: 'dignityScore',
  createdAt: 'createdAt'
};

exports.Prisma.HousePositionScalarFieldEnum = {
  id: 'id',
  birthChartId: 'birthChartId',
  house: 'house',
  zodiacSign: 'zodiacSign',
  degree: 'degree',
  size: 'size',
  planets: 'planets',
  createdAt: 'createdAt'
};

exports.Prisma.AspectScalarFieldEnum = {
  id: 'id',
  birthChartId: 'birthChartId',
  planet1: 'planet1',
  planet2: 'planet2',
  aspectType: 'aspectType',
  orb: 'orb',
  orbQuality: 'orbQuality',
  strength: 'strength',
  isApplying: 'isApplying',
  isSeparating: 'isSeparating',
  isMajor: 'isMajor',
  isHarmonic: 'isHarmonic',
  createdAt: 'createdAt'
};

exports.Prisma.AstrologyReadingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  birthChartId: 'birthChartId',
  readingType: 'readingType',
  title: 'title',
  status: 'status',
  summary: 'summary',
  introduction: 'introduction',
  mainContent: 'mainContent',
  conclusion: 'conclusion',
  personalityProfile: 'personalityProfile',
  careerGuidance: 'careerGuidance',
  relationships: 'relationships',
  lifeChallenges: 'lifeChallenges',
  spiritualPath: 'spiritualPath',
  healthWellness: 'healthWellness',
  financialProsperity: 'financialProsperity',
  timingForecast: 'timingForecast',
  aiModel: 'aiModel',
  promptUsed: 'promptUsed',
  processingTime: 'processingTime',
  confidenceScore: 'confidenceScore',
  isFavorited: 'isFavorited',
  userRating: 'userRating',
  userNotes: 'userNotes',
  isPublic: 'isPublic',
  shareId: 'shareId',
  viewCount: 'viewCount',
  tags: 'tags',
  keywords: 'keywords',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completedAt: 'completedAt'
};

exports.Prisma.TransitChartScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  birthChartId: 'birthChartId',
  transitDate: 'transitDate',
  significantEvents: 'significantEvents',
  aiAnalysis: 'aiAnalysis',
  createdAt: 'createdAt'
};

exports.Prisma.TransitPlanetPositionScalarFieldEnum = {
  id: 'id',
  transitChartId: 'transitChartId',
  planet: 'planet',
  zodiacSign: 'zodiacSign',
  degree: 'degree',
  isRetrograde: 'isRetrograde',
  createdAt: 'createdAt'
};

exports.Prisma.TransitAspectScalarFieldEnum = {
  id: 'id',
  transitChartId: 'transitChartId',
  aspectCategory: 'aspectCategory',
  planet1: 'planet1',
  planet2: 'planet2',
  planet1Type: 'planet1Type',
  planet2Type: 'planet2Type',
  aspectType: 'aspectType',
  orb: 'orb',
  isApplying: 'isApplying',
  significance: 'significance',
  themes: 'themes',
  createdAt: 'createdAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  token: 'token',
  expires: 'expires',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PricingPlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  planType: 'planType',
  status: 'status',
  isPopular: 'isPopular',
  displayOrder: 'displayOrder',
  price: 'price',
  currency: 'currency',
  billingPeriod: 'billingPeriod',
  originalPrice: 'originalPrice',
  discount: 'discount',
  shortDescription: 'shortDescription',
  longDescription: 'longDescription',
  ctaText: 'ctaText',
  ctaLink: 'ctaLink',
  maxGenerationsPerMonth: 'maxGenerationsPerMonth',
  maxGenerationsPerDay: 'maxGenerationsPerDay',
  maxStorageMB: 'maxStorageMB',
  maxHairstyleGenerations: 'maxHairstyleGenerations',
  maxMakeupGenerations: 'maxMakeupGenerations',
  maxHomeDecoGenerations: 'maxHomeDecoGenerations',
  maxLinkedInGenerations: 'maxLinkedInGenerations',
  maxBirthChartGenerations: 'maxBirthChartGenerations',
  maxAstrologyReadings: 'maxAstrologyReadings',
  maxTransitCharts: 'maxTransitCharts',
  maxCompatibilityCharts: 'maxCompatibilityCharts',
  features: 'features',
  featureFlags: 'featureFlags',
  allowedImageQualities: 'allowedImageQualities',
  defaultImageQuality: 'defaultImageQuality',
  supportLevel: 'supportLevel',
  responseTime: 'responseTime',
  dedicatedSupport: 'dedicatedSupport',
  accountManager: 'accountManager',
  apiAccess: 'apiAccess',
  whiteLabel: 'whiteLabel',
  customIntegrations: 'customIntegrations',
  batchProcessing: 'batchProcessing',
  priorityProcessing: 'priorityProcessing',
  trialDays: 'trialDays',
  setupFee: 'setupFee',
  requiresApproval: 'requiresApproval',
  maxUsers: 'maxUsers',
  maxProjects: 'maxProjects',
  tags: 'tags',
  badge: 'badge',
  icon: 'icon',
  color: 'color',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  keywords: 'keywords',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NativityChartScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  description: 'description',
  birthDateTime: 'birthDateTime',
  birthTimestamp: 'birthTimestamp',
  timeResolution: 'timeResolution',
  coordinateSystem: 'coordinateSystem',
  latitude: 'latitude',
  longitude: 'longitude',
  timezone: 'timezone',
  locationName: 'locationName',
  isPublic: 'isPublic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EphemerisSnapshotScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  absoluteTimeIndex: 'absoluteTimeIndex',
  phase: 'phase',
  createdAt: 'createdAt'
};

exports.Prisma.PlanetDataScalarFieldEnum = {
  id: 'id',
  ephemerisSnapshotId: 'ephemerisSnapshotId',
  planet: 'planet',
  longitude: 'longitude',
  latitude: 'latitude',
  speed: 'speed',
  acceleration: 'acceleration',
  direction: 'direction',
  stationaryEnterTime: 'stationaryEnterTime',
  stationaryExitTime: 'stationaryExitTime',
  houseCusp: 'houseCusp',
  houseDegree: 'houseDegree',
  houseSign: 'houseSign',
  relativeAngularIndex: 'relativeAngularIndex',
  createdAt: 'createdAt'
};

exports.Prisma.GeometryIndexScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  clusterHash: 'clusterHash',
  createdAt: 'createdAt'
};

exports.Prisma.AngularDistanceScalarFieldEnum = {
  id: 'id',
  geometryIndexId: 'geometryIndexId',
  planet1: 'planet1',
  planet2: 'planet2',
  distance: 'distance',
  minDistance: 'minDistance',
  maxDistance: 'maxDistance',
  speedWeighting: 'speedWeighting',
  createdAt: 'createdAt'
};

exports.Prisma.NativityAspectScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  geometryIndexId: 'geometryIndexId',
  planet1: 'planet1',
  planet2: 'planet2',
  aspectType: 'aspectType',
  orbDistance: 'orbDistance',
  isApplying: 'isApplying',
  exactnessScore: 'exactnessScore',
  exactDateTime: 'exactDateTime',
  buildUpStart: 'buildUpStart',
  decayEnd: 'decayEnd',
  orbStrength: 'orbStrength',
  speedWeighting: 'speedWeighting',
  planet1ProfileId: 'planet1ProfileId',
  planet2ProfileId: 'planet2ProfileId',
  createdAt: 'createdAt'
};

exports.Prisma.PlanetaryProfileScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  planet: 'planet',
  primaryDomain: 'primaryDomain',
  secondaryDomain: 'secondaryDomain',
  dignity: 'dignity',
  strength: 'strength',
  speed: 'speed',
  visibility: 'visibility',
  expressionBandwidth: 'expressionBandwidth',
  saturationLevel: 'saturationLevel',
  distortionFactor: 'distortionFactor',
  housePosition: 'housePosition',
  signPosition: 'signPosition',
  createdAt: 'createdAt'
};

exports.Prisma.StateVectorScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  timestamp: 'timestamp',
  timestampMicro: 'timestampMicro',
  planetaryStates: 'planetaryStates',
  aspectStates: 'aspectStates',
  outcomes: 'outcomes',
  decisions: 'decisions',
  narratives: 'narratives',
  eventLayer: 'eventLayer',
  patternLayer: 'patternLayer',
  archetypeLayer: 'archetypeLayer',
  confidenceLevel: 'confidenceLevel',
  entropyScore: 'entropyScore',
  createdAt: 'createdAt'
};

exports.Prisma.PurposeStateScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  timestamp: 'timestamp',
  timestampMicro: 'timestampMicro',
  planetaryStates: 'planetaryStates',
  aspectStates: 'aspectStates',
  outcomes: 'outcomes',
  decisions: 'decisions',
  narratives: 'narratives',
  intentSignals: 'intentSignals',
  priorityWeights: 'priorityWeights',
  constraintFlags: 'constraintFlags',
  purposeVector: 'purposeVector',
  vectorVersion: 'vectorVersion',
  computedAt: 'computedAt',
  confidenceLevel: 'confidenceLevel',
  entropyScore: 'entropyScore',
  createdAt: 'createdAt'
};

exports.Prisma.SimilarityRecordScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  similarTo: 'similarTo',
  similarityScore: 'similarityScore',
  speedWeighting: 'speedWeighting',
  phaseWeighting: 'phaseWeighting',
  orbWeighting: 'orbWeighting',
  queryType: 'queryType',
  createdAt: 'createdAt'
};

exports.Prisma.CurrentStoryScalarFieldEnum = {
  id: 'id',
  nativityChartId: 'nativityChartId',
  transitDate: 'transitDate',
  userLatitude: 'userLatitude',
  userLongitude: 'userLongitude',
  userTimeZone: 'userTimeZone',
  storyState: 'storyState',
  mainNarrative: 'mainNarrative',
  overallIntensity: 'overallIntensity',
  themes: 'themes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.PlanetarySceneScalarFieldEnum = {
  id: 'id',
  currentStoryId: 'currentStoryId',
  planet: 'planet',
  sign: 'sign',
  house: 'house',
  natalLongitude: 'natalLongitude',
  currentLongitude: 'currentLongitude',
  movementDegrees: 'movementDegrees',
  intensity: 'intensity',
  dominantPressure: 'dominantPressure',
  behavioralPattern: 'behavioralPattern',
  externalConflict: 'externalConflict',
  relationshipEffect: 'relationshipEffect',
  pressureDirection: 'pressureDirection',
  collapseRisk: 'collapseRisk',
  momentumDirection: 'momentumDirection',
  storyFunction: 'storyFunction',
  activeAspects: 'activeAspects',
  sceneAttributes: 'sceneAttributes',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};
exports.UtilityType = exports.$Enums.UtilityType = {
  HAIRSTYLE: 'HAIRSTYLE',
  MAKEUP: 'MAKEUP',
  HOME_DECO: 'HOME_DECO',
  LINKEDIN: 'LINKEDIN',
  ASTROLOGY_BIRTH_CHART: 'ASTROLOGY_BIRTH_CHART',
  ASTROLOGY_READING: 'ASTROLOGY_READING',
  ASTROLOGY_TRANSIT: 'ASTROLOGY_TRANSIT',
  ASTROLOGY_COMPATIBILITY: 'ASTROLOGY_COMPATIBILITY'
};

exports.GenerationMode = exports.$Enums.GenerationMode = {
  PRESETS: 'PRESETS',
  CUSTOM: 'CUSTOM',
  MIX_PHOTO: 'MIX_PHOTO'
};

exports.GenerationStatus = exports.$Enums.GenerationStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

exports.FileType = exports.$Enums.FileType = {
  SOURCE_IMAGE: 'SOURCE_IMAGE',
  RESULT_IMAGE: 'RESULT_IMAGE',
  REFERENCE_IMAGE: 'REFERENCE_IMAGE',
  DOCUMENT: 'DOCUMENT'
};

exports.FileStatus = exports.$Enums.FileStatus = {
  UPLOADING: 'UPLOADING',
  UPLOADED: 'UPLOADED',
  PROCESSING: 'PROCESSING',
  FAILED: 'FAILED'
};

exports.PlanType = exports.$Enums.PlanType = {
  FREE: 'FREE',
  BASIC: 'BASIC',
  PREMIUM: 'PREMIUM',
  ENTERPRISE: 'ENTERPRISE'
};

exports.SubscriptionStatus = exports.$Enums.SubscriptionStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  SUSPENDED: 'SUSPENDED'
};

exports.ReadingType = exports.$Enums.ReadingType = {
  PERSONALITY_PROFILE: 'PERSONALITY_PROFILE',
  CAREER_GUIDANCE: 'CAREER_GUIDANCE',
  RELATIONSHIP_COMPATIBILITY: 'RELATIONSHIP_COMPATIBILITY',
  LIFE_CHALLENGES: 'LIFE_CHALLENGES',
  SPIRITUAL_PATH: 'SPIRITUAL_PATH',
  HEALTH_WELLNESS: 'HEALTH_WELLNESS',
  FINANCIAL_PROSPERITY: 'FINANCIAL_PROSPERITY',
  TIMING_FORECAST: 'TIMING_FORECAST',
  COMPREHENSIVE_ANALYSIS: 'COMPREHENSIVE_ANALYSIS'
};

exports.AspectType = exports.$Enums.AspectType = {
  CONJUNCTION: 'CONJUNCTION',
  SEXTILE: 'SEXTILE',
  SQUARE: 'SQUARE',
  TRINE: 'TRINE',
  OPPOSITION: 'OPPOSITION',
  QUINCUNX: 'QUINCUNX',
  SEMISEXTILE: 'SEMISEXTILE',
  SEMISQUARE: 'SEMISQUARE',
  SESQUIQUADRATE: 'SESQUIQUADRATE',
  QUINTILE: 'QUINTILE',
  BIQUINTILE: 'BIQUINTILE'
};

exports.ChartType = exports.$Enums.ChartType = {
  NATAL: 'NATAL',
  TRANSIT: 'TRANSIT',
  PROGRESSION: 'PROGRESSION',
  SOLAR_RETURN: 'SOLAR_RETURN',
  LUNAR_RETURN: 'LUNAR_RETURN',
  COMPOSITE: 'COMPOSITE',
  SYNASTRY: 'SYNASTRY'
};

exports.ZodiacSign = exports.$Enums.ZodiacSign = {
  ARIES: 'ARIES',
  TAURUS: 'TAURUS',
  GEMINI: 'GEMINI',
  CANCER: 'CANCER',
  LEO: 'LEO',
  VIRGO: 'VIRGO',
  LIBRA: 'LIBRA',
  SCORPIO: 'SCORPIO',
  SAGITTARIUS: 'SAGITTARIUS',
  CAPRICORN: 'CAPRICORN',
  AQUARIUS: 'AQUARIUS',
  PISCES: 'PISCES'
};

exports.Planet = exports.$Enums.Planet = {
  SUN: 'SUN',
  MOON: 'MOON',
  MERCURY: 'MERCURY',
  VENUS: 'VENUS',
  MARS: 'MARS',
  JUPITER: 'JUPITER',
  SATURN: 'SATURN',
  URANUS: 'URANUS',
  NEPTUNE: 'NEPTUNE',
  PLUTO: 'PLUTO',
  NORTH_NODE: 'NORTH_NODE',
  SOUTH_NODE: 'SOUTH_NODE',
  ASCENDANT: 'ASCENDANT',
  MIDHEAVEN: 'MIDHEAVEN',
  DESCENDANT: 'DESCENDANT',
  IC: 'IC'
};

exports.House = exports.$Enums.House = {
  HOUSE_1: 'HOUSE_1',
  HOUSE_2: 'HOUSE_2',
  HOUSE_3: 'HOUSE_3',
  HOUSE_4: 'HOUSE_4',
  HOUSE_5: 'HOUSE_5',
  HOUSE_6: 'HOUSE_6',
  HOUSE_7: 'HOUSE_7',
  HOUSE_8: 'HOUSE_8',
  HOUSE_9: 'HOUSE_9',
  HOUSE_10: 'HOUSE_10',
  HOUSE_11: 'HOUSE_11',
  HOUSE_12: 'HOUSE_12'
};

exports.PlanetElement = exports.$Enums.PlanetElement = {
  FIRE: 'FIRE',
  EARTH: 'EARTH',
  AIR: 'AIR',
  WATER: 'WATER'
};

exports.PlanetQuality = exports.$Enums.PlanetQuality = {
  CARDINAL: 'CARDINAL',
  FIXED: 'FIXED',
  MUTABLE: 'MUTABLE'
};

exports.AspectOrb = exports.$Enums.AspectOrb = {
  TIGHT: 'TIGHT',
  MEDIUM: 'MEDIUM',
  WIDE: 'WIDE',
  VERY_WIDE: 'VERY_WIDE'
};

exports.ReadingStatus = exports.$Enums.ReadingStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

exports.PricingPlanStatus = exports.$Enums.PricingPlanStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ARCHIVED: 'ARCHIVED'
};

exports.BillingPeriod = exports.$Enums.BillingPeriod = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
  LIFETIME: 'LIFETIME',
  ONE_TIME: 'ONE_TIME'
};

exports.TimeResolution = exports.$Enums.TimeResolution = {
  MINUTE: 'MINUTE',
  SECOND: 'SECOND',
  EVENT_BASED: 'EVENT_BASED'
};

exports.CoordinateSystem = exports.$Enums.CoordinateSystem = {
  SIDEREAL: 'SIDEREAL',
  TROPICAL: 'TROPICAL'
};

exports.PlanetDirection = exports.$Enums.PlanetDirection = {
  DIRECT: 'DIRECT',
  RETROGRADE: 'RETROGRADE',
  STATIONARY: 'STATIONARY'
};

exports.Prisma.ModelName = {
  User: 'User',
  AIGeneration: 'AIGeneration',
  UploadedFile: 'UploadedFile',
  Subscription: 'Subscription',
  UsageLog: 'UsageLog',
  UserPreferences: 'UserPreferences',
  BirthChart: 'BirthChart',
  PlanetPosition: 'PlanetPosition',
  HousePosition: 'HousePosition',
  Aspect: 'Aspect',
  AstrologyReading: 'AstrologyReading',
  TransitChart: 'TransitChart',
  TransitPlanetPosition: 'TransitPlanetPosition',
  TransitAspect: 'TransitAspect',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  PricingPlan: 'PricingPlan',
  NativityChart: 'NativityChart',
  EphemerisSnapshot: 'EphemerisSnapshot',
  PlanetData: 'PlanetData',
  GeometryIndex: 'GeometryIndex',
  AngularDistance: 'AngularDistance',
  NativityAspect: 'NativityAspect',
  PlanetaryProfile: 'PlanetaryProfile',
  StateVector: 'StateVector',
  PurposeState: 'PurposeState',
  SimilarityRecord: 'SimilarityRecord',
  CurrentStory: 'CurrentStory',
  PlanetaryScene: 'PlanetaryScene'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
